# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

dist: xenial

branches:
  only:
    - master
    - develop
    - /feature\/.*/

env:
  matrix:
    - BOGUS_JOB=true

matrix:
  exclude:
    - env: BOGUS_JOB=true

  include:

    - env: LIB=assert COMMENT=trusty
      dist: trusty
      compiler: g++

    - env: LIB=assert COMMENT=trusty
      dist: trusty
      compiler: clang++

    - env: LIB=assert COMMENT=xenial
      dist: xenial
      compiler: g++

    - env: LIB=assert COMMENT=xenial
      dist: xenial
      compiler: clang++

    - env: LIB=assert COMMENT=bionic
      dist: bionic
      compiler: g++

    - env: LIB=assert COMMENT=bionic
      dist: bionic
      compiler: clang++

    - env: LIB=assert
      os: osx

    - env: LIB=timer
      compiler: g++

    - env: LIB=timer BUILD_SHARED_LIBS=ON
      compiler: g++

    - env: LIB=timer
      compiler: clang++

    - env: LIB=timer BUILD_SHARED_LIBS=ON
      compiler: clang++

    - env: LIB=timer
      os: osx

    - env: LIB=timer BUILD_SHARED_LIBS=ON
      os: osx

    - env: TEST_BOOST_TEST=1 LIB=core
      script:
        - cd tools/cmake/test/boost_test
        - mkdir __build__ && cd __build__
        - cmake -DBoost_VERBOSE=ON ..
        - ctest --output-on-failure

    - env: TEST_BOOST_FETCH=1
      install: true
      script:
        - cd test/boost_fetch
        - mkdir __build__ && cd __build__
        - cmake ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=mp11 BOOST_INCLUDE_LIBRARIES=mp11
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=assert BOOST_INCLUDE_LIBRARIES="assert;config"
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=assert BOOST_INCLUDE_LIBRARIES="assert;config" BOOST_INSTALL_LAYOUT=tagged
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=assert BOOST_INCLUDE_LIBRARIES="assert;config" BOOST_INSTALL_LAYOUT=versioned
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=atomic BOOST_INCLUDE_LIBRARIES="assert;atomic;config;static_assert;type_traits"
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=atomic BOOST_INCLUDE_LIBRARIES="assert;atomic;config;static_assert;type_traits" BOOST_INSTALL_LAYOUT=tagged BUILD_SHARED_LIBS=ON
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

    - env: TEST_BOOST_INSTALL=1 LIB=atomic BOOST_INCLUDE_LIBRARIES="assert;atomic;config;static_assert;type_traits" BOOST_INSTALL_LAYOUT=versioned
      script:
        - mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=$BOOST_INCLUDE_LIBRARIES ${BOOST_INSTALL_LAYOUT:+-DBOOST_INSTALL_LAYOUT=$BOOST_INSTALL_LAYOUT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
        - cmake --build . --target install
        - cd ../tools/cmake/test/$LIB && mkdir __build__ && cd __build__
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        - cmake --build .
        - cmake --build . --target check

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init --jobs 3 tools/boostdep libs/$LIB
  - python tools/boostdep/depinst/depinst.py -g "--jobs 3" $LIB
  - rm -rf tools/cmake/*
  - cp -r $TRAVIS_BUILD_DIR/* tools/cmake

script:
  - mkdir __build__ && cd __build__
  - cmake -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=ON -DBOOST_INCLUDE_LIBRARIES=${BOOST_INCLUDE_LIBRARIES:-$LIB} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} ..
  - cmake --build .
  - ctest --output-on-failure -R boost_$LIB

notifications:
  email:
    on_success: always
