# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/

image: Visual Studio 2017

environment:
  matrix:
  - LIB: assert
  - LIB: assert
    BOOST_INCLUDE_LIBRARIES: assert
  - LIB: timer
  - LIB: timer
    BUILD_SHARED_LIBS: ON
  - LIB: timer
    BOOST_INCLUDE_LIBRARIES: timer
  - LIB: timer
    BUILD_SHARED_LIBS: ON
    BOOST_INCLUDE_LIBRARIES: timer

install:
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - cd ..
  - git clone -b %BOOST_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init --jobs 3 tools/boostdep libs/%LIB%
  - python tools/boostdep/depinst/depinst.py -g "--jobs 3" %LIB%
  - rd /s/q tools\cmake
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% tools\cmake\

build: off

test_script:
  - mkdir __build__ && cd __build__
  - if "%BUILD_SHARED_LIBS%" == "" SET BUILD_SHARED_LIBS=0
  - if NOT "%BOOST_INCLUDE_LIBRARIES%" == "" SET BOOST_INCLUDE_LIBRARIES=-DBOOST_INCLUDE_LIBRARIES=%BOOST_INCLUDE_LIBRARIES%
  - cmake -DBOOST_ENABLE_CMAKE=1 -DBoost_DEBUG=ON -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% %BOOST_INCLUDE_LIBRARIES% ..
  - cmake --build . --config Debug && ctest --output-on-failure -R boost_%LIB% -C Debug
  - cmake --build . --config Release && ctest --output-on-failure -R boost_%LIB% -C Release
  - cmake --build . --config MinSizeRel && ctest --output-on-failure -R boost_%LIB% -C MinSizeRel
  - cmake --build . --config RelWithDebInfo && ctest --output-on-failure -R boost_%LIB% -C RelWithDebInfo
